### ISSUE TITLE
[FEAT] 회원가입

### ISSUE THREAD

**Issue by jamie9504** [woowacourse-teams/2020-legeno-around-here#2]
**Subject**
- 회원가입을 한다.

**Detail**
- 이메일, 비밀번호, 닉네임을 입력하여 회원 가입할 수 있다.
- 닉네임은 중복될 수 있다.

**Reference**
- write here

**Comment by Hamliet** [comment]
작업 중입니다.

**Comment by Hamliet** [comment]
이슈 완료로 close 합니다.
