### ISSUE TITLE
[FEAT] 프로필 수정 / 회원 탈퇴

### ISSUE THREAD

**Issue by jamie9504** [woowacourse-teams/2020-legeno-around-here#9]
**Subject**
- 유저의 프로필을 수정한다.
- 회원 탈퇴한다.

**Detail**
- 사용자가 등록한 사진 및 닉네임을 수정할 수 있다.
- 사용자가 회원 탈퇴할 수 있다.

**Reference**
- write here

**Comment by Hamliet** [comment]
작업 중입니다.
